<?php
//$home 		= "http://localhost/portalAuditoriaVisual/";
global $home;
$RutaFisica	= "../../../";

	// Variables de Ubicacion para almacenar imagenes
	$cRutaImgGeneral			 	= $RutaFisica . "fotos/Image/";		// Modulo Categorias Productos
	$cRutaImgCategorias_Productos 	= $RutaFisica . "fotos/Image/categoriasprod/";		// Modulo Categorias Productos
	$cRutaImgProductos				= $RutaFisica . "fotos/Image/productos/";			// Modulo Productos
	$cRutaImgProductosPequenia		= $RutaFisica . "fotos/Image/productos/pequenia/";	// Modulo Pequenia
	$cRutaImgCategorias_Servicios 	= $RutaFisica . "fotos/Image/categoriasser/";		// Modulo Categorias Servicios
	$cRutaImgServicios				= $RutaFisica . "fotos/Image/servicios/";			// Modulo Servicios
	$cRutaImgNoticias				= $RutaFisica . "fotos/Image/noticias/";			// Modulo Noticias
	$cRutaImgBoletines				= $RutaFisica . "fotos/Image/boletines/";			// Modulo Boletines
	$cRutaImgAgendas				= $RutaFisica . "fotos/Image/agendas/";				// Modulo Agendas
	$cRutaImgEmpsemana				= $RutaFisica . "fotos/Image/empsemana/";			// Modulo Empresa de la semana
	$cRutaImgOfertasemana			= $RutaFisica . "fotos/Image/ofertasemana/";		// Modulo Ofertas de la semana
	$cRutaImgEmpaisas				= $RutaFisica . "fotos/Image/empresaspaisas/";		// Modulo Empresas Paisas
	$cRutaImgContenidos				= $RutaFisica . "fotos/Image/contenidos/";			// Modulo Contenidos
	$cRutaImgEditorial				= $RutaFisica . "fotos/Image/editorial/";			// Modulo Editorial
	$cRutaImgEventos				= $RutaFisica . "fotos/Image/eventos/";				// Modulo Eventos
	$cRutaImgMenu					= $RutaFisica . "fotos/Image/menu/";				// Modulo Menu
	$cRutaImgCategorias_Eventos 	= $RutaFisica . "fotos/Image/categoriasev/";		// Modulo Categorias Eventos
	$cRutaImgSitios					= $RutaFisica . "fotos/Image/sitiossugeridos/";		// Modulo Sitios
	$cRutaImgCategorias_Profesionales 	= $RutaFisica . "fotos/Image/categoriaspro/";		// Modulo Categorias Profesionales
	$cRutaImgCategorias_Galeria   	= $RutaFisica . "fotos/Image/categoriasgale/";		// Modulo Categorias Geleria de Imagenes
	$cRutaImgMusica					= $RutaFisica . "fotos/Image/musica/";				// Modulo Música
	$cRutaImgGaleria				= $RutaFisica . "fotos/Image/galeria/";				// Modulo Galeria de Imagenes
	$cRutaTarjetas				    = $RutaFisica . "fotos/Image/tarjetas/";			// Modulo Galeria de Tarjetas
    $cRutaImgPlanes					= $RutaFisica . "fotos/Image/planes/";				// Modulo Galeria de Imagenes
	$cRutaImgClientes				= $RutaFisica . "fotos/Image/imgclientes/";			// Modulos Especial Clientes Imagenes
	$cRutaArchivos					= $RutaFisica . "fotos/Image/archivos/";			// Modulos Archivos
	$cRutaImgCategorias_Archivos	= $RutaFisica . "fotos/Image/arhivos/";				// Modulo Categorias Archivos
	$cRutaBanners					= $RutaFisica . "fotos/Image/banners/";				// Modulo Banners
	$ccRutaBanners					=  "../fotos/Image/banners/";						// Solución de problema de imágenes
	$cRutaImgImage					= $RutaFisica . "fotos/Image/image/";				// Modulo Banners
	$cRutaLogoCarrito				= $RutaFisica . "fotos/Image/carrito/";				// Logo Empresa Carrito
	$cRutaPlantillas_GenBoletines	= $RutaFisica . "fotos/Image/plantillasgb/";
    $cRutaImgCabezotes 	            = $RutaFisica . "fotos/Image/cabezotes/";			// Modulo Cabezotes
    $cRutaImgCabezotesjq 	        = $RutaFisica . "fotos/Image/cabezotesjq/";			// Modulo Cabezotesjq
    $cRutaImgCabezoteUser 	        = $RutaFisica . "fotos/portadas/";		// Modulo Cabezotesjq
    $cRutaImagenDirEmp              = $RutaFisica."fotos/Image/directorio_empresarial/";
    $cRutaImagenDirEmpPub           = "../fotos/Image/directorio_empresarial/";
	$cRutaImagenTienda      		= $RutaFisica."fotos/tienda/productos/";			// Modulo Tienda
	$cRutaImagenMarcas      		= $RutaFisica."fotos/tienda/marcas/";				// Modulo Tienda
	$cRutaImagenEspec      		= $RutaFisica."fotos/tienda/espec/";				// Modulo Tienda
	$cRutaTicketsAdjunto    		= $RutaFisica."fotos/tickets/";						// Modulo Tickets
	$cRutaImgMbContenidos 			= $RutaFisica . "fotos/mb_contenidos/";   	    	// Modulo Membresias Contenidos
	$cRutaImgMbArchivos				= $RutaFisica . "fotos/mb_contenidos/";  			// Modulo Membresias Archivos
	$cRutaImgCinta					= $RutaFisica . "fotos/Image/imagenescinta/";  		// Modulo Cinta
	$cRutaImgFondos					= $RutaFisica . "fotos/Image/fondos/";  			// Modulo Fondos
	$cRutaImgMenu					= $RutaFisica . "fotos/Image/menu/";				// Modulo Menu
	$cRutaFirmas		    		= $RutaFisica . "fotos/Image/firmas/";				// Modulo Usuarios
	$cRutaPlantillas	 			= $RutaFisica . "fotos/Image/plantillas/";   	    // Modulo Plantillas
	$cRutaDocumentos				= $RutaFisica . "fotos/documentos/";  				// Modulo Documentos
	$cRutaEstilos					= $RutaFisica . "estilos/";  						// Modulo Estilos

	// Variables para obtener acceso a las imagenes almacenadas
	$cRutaVerImgGeneral			 		= $home . "/fotos/Image/";		// Modulo Categorias Productos
	$cRutaVerImgCategorias_Productos	= $home . "/fotos/Image/categoriasprod/";		// Modulo Categorias Productos
	$cRutaVerImgProductos				= $home . "/fotos/Image/productos/";			// Modulo Productos
	$cRutaVerImgProductosPequenia		= $home . "/fotos/Image/productos/pequenia/";	// Modulo Pequenia
	$cRutaVerImgCategorias_Servicios 	= $home . "/fotos/Image/categoriasser/";		// Modulo Categorias Servicios
	$cRutaVerImgServicios				= $home . "/fotos/Image/servicios/";			// Modulo Servicios
	$cRutaVerImgNoticias				= $home . "/fotos/Image/noticias/";			// Modulo Noticias
	$cRutaVerImgBoletines				= $home . "/fotos/Image/boletines/";			// Modulo Boletines
	$cRutaVerImgAgendas					= $home . "/fotos/Image/agendas/";			// Modulo Agendas
	$cRutaVerImgEmpsemana				= $home . "/fotos/Image/empsemana/";			// Modulo Empresa de la semana
	$cRutaVerImgOfertasemana			= $home . "/fotos/Image/ofertasemana/";		// Modulo Ofertas de la semana
	$cRutaVerImgEmpaisas				= $home . "/fotos/Image/empresaspaisas/";		// Modulo Empresas Paisas
	$cRutaVerImgContenidos				= $home . "/fotos/Image/contenidos/";			// Modulo Contenidos
	$cRutaVerImgEditorial				= $home . "/fotos/Image/editorial/";			// Modulo Editorial
	$cRutaVerImgEventos					= $home . "/fotos/Image/eventos/";			// Modulo Editorial
	$cRutaVerImgMenu					= $home . "/fotos/Image/menu/";				// Modulo Menu
	$cRutaVerImgCategorias_Eventos 		= $home . "/fotos/Image/categoriasev/";		// Modulo Categorias Eventos
	$cRutaVerImgSitios					= $home . "/fotos/Image/sitiossugeridos/";	// Modulo Editorial
	$cRutaVerImgCategorias_Galeria		= $home . "/fotos/Image/categoriasgale/";		// Modulo Categorias Galeria Imagenes
	$cRutaVerImgGaleria					= $home . "/fotos/Image/galeria/";			// Modulo Galeria de Imagenes
    $cRutaVerTarjetas					= $home . "/fotos/Image/tarjetas/";			// Modulo Galeria de Imagenes
	$cRutaVerImgPlanes					= $home . "/fotos/Image/planes/";				// Modulo Galeria de Imagenes
	$cRutaVerImgClientes				= $home . "/fotos/Image/imgclientes/";		// Modulos Especial Clientes Imagenes
	$cRutaVerArchivos					= $home . "/fotos/Image/archivos/";			// Modulos Archivos
	$cRutaVerImgCategorias_Archivos		= $home . "/fotos/Image/archivos/";			// Modulo Categorias Archivos
	$cRutaVerBanners					= $home . "/fotos/Image/banners/";			// Modulo Banners
	$cRutaVerImage						= $home . "/fotos/Image/image/";				// Modulo Banners
	$cRutaVerLogoCarrito				= $home . "/fotos/Image/carrito/";			// Logo Empresa Carrito
	$cRutaVerPlantillas_GenBoletines	= $home . "/fotos/Image/plantillasgb/";
    $cRutaVerCabezotes 	     	      	= $home . "/fotos/Image/cabezotes/";			// Modulo Cabezotes
    $cRutaVerCabezotesjq 	     	    = $home . "/fotos/Image/cabezotesjq/";		// Modulo Cabezotesjq
    $cRutaVerImagenDirEmp               = $home . "/fotos/Image/directorio_empresarial/";
	$cRutaVerImagenTienda      			= $home . "/fotos/tienda/productos/";			// Modulo Tienda
	$cRutaVerImagenMarcas      			= $home . "/fotos/tienda/marcas/";				// Modulo Marcas
	$cRutaVerTicketsAdjunto    			= $home . "/fotos/tickets/";					// Modulo Tickets
	$cRutaVerImgMbContenidos 			= $home . "/fotos/mb_contenidos/";			// Modulo Membresias Contenidos
	$cRutaVerImgMbArchivos 				= $home . "/fotos/mb_contenidos/";			// Modulo Membresias Archivos
	$cRutaVerImgCinta					= $home . "/fotos/Image/imagenescinta/";		// Modulo Cinta Transportadora
	$cRutaVerImgMusica					= $home . "/fotos/Image/musica/";				// Modulo Música
	$cRutaVerImgFondos					= $home . "/fotos/Image/fondos/";  			// Modulo Fondos
	$cRutaVerImgMenu					= $home . "/fotos/Image/menu/";				// Modulo Menu
	$cRutaVerFirmas		    			= $home . "/fotos/Image/firmas/";				// Modulo Usuarios
	$cRutaVerPlantillas	 				= $home . "/fotos/Image/plantillas/";   	    // Modulo Plantillas
	$cRutaVerDocumentos					= $home . "/fotos/documentos/";  				// Modulo Documentos
	$cRutaVerEstilos					= $home . "/estilos/";  						// Modulo Estilos

?>